# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ice-bank-api:
    build:
      target: development
    image: ffc-ice-bank-api-development
    container_name: ffc-ice-bank-api-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
