services:
  ffc-ice-bank-api:
    build:
      context: .
      target: production
    image: ffc-ice-bank-api
    container_name: ffc-ice-bank-api
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ice-bank-api-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
