{{- include "ffc-helm-library.container-secret" (list . "ffc-ice-bank-api.container-secret") -}}
{{- define "ffc-ice-bank-api.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  {{- if .Values.container.d365TenantID }}
  D365_TENANT_ID: {{ quote .Values.container.d365TenantID }}
  {{- end }}
  {{- if .Values.container.d365ClientID }}
  D365_CLIENT_ID: {{ quote .Values.container.d365ClientID }}
  {{- end }}
  {{- if .Values.container.d365ClientSecret }}
  D365_CLIENT_SECRET: {{ quote .Values.container.d365ClientSecret }}
  {{- end }}
  {{- if .Values.container.apiKey }}
  API_KEY: {{ quote .Values.container.apiKey }}
  {{- end }}
{{- end -}}
