apiVersion: v2
description: Microservice responsible for communicating with d365 and returning the response to portal frontend
name: ffc-ice-bank-api
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 4.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
