environment: production
environmentCode:
name: ffc-ice-bank-api
namespace: ffc-ice
workstream: ffc-ice
image: ffc-ice-bank-api

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-ice-bank-api-config-map

containerSecret:
  name: ffc-ice-bank-api-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  apiKey:
  d365ApiHost:
  d365ApiUrl:
  d365TenantID:
  d365ClientID:
  d365ClientSecret:

ingress:
  class: nginx
  endpoint: ffc-ice-bank-api
  server: example.com  

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
